CREATE TABLE GAME ("ID" INTEGER not null primary key, "TITLE" VARCHAR(50) not null, "DESCRIPTIONHTML" VARCHAR(2000), "COVER" VARCHAR(200), "SCREENSHOT" VARCHAR(200))
CREATE TABLE DETAIL ("ID" INTEGER not null primary key, "DIRECTOR" VARCHAR(50) not null, "YEAR" INT, "TYPE" VARCHAR(20), "PUBLISHER" VARCHAR(50))
CREATE TABLE REVIEW ("ID" INTEGER not null primary key, "REVIEW" VARCHAR(500) not null, "REVIEWER" VARCHAR(100) not null, "RATING" INT not null, "GAMEID" INT not null);

ALTER TABLE DETAIL ADD CONSTRAINT FK_Detail_Game FOREIGN KEY(ID) REFERENCES GAME(ID)
ALTER TABLE REVIEW ADD CONSTRAINT FK_Review_Game FOREIGN KEY(GAMEID) REFERENCES GAME(ID)