CREATE SCHEMA IF NOT EXISTS GAMES
CREATE TABLE GAMES.GAME ("ID" INTEGER not null primary key, "TITLE" VARCHAR(50) not null, "DESCRIPTIONHTML" VARCHAR(2000), "COVER" VARCHAR(200), "SCREENSHOT" VARCHAR(200))

CREATE SCHEMA IF NOT EXISTS DETAILS
CREATE TABLE DETAILS.DETAIL ("ID" INTEGER not null primary key, "DIRECTOR" VARCHAR(50) not null, "YEAR" INT, "TYPE" VARCHAR(20), "PUBLISHER" VARCHAR(50))

CREATE SCHEMA IF NOT EXISTS REVIEWS
CREATE TABLE REVIEWS.REVIEW ("ID" INTEGER not null primary key, "REVIEW" VARCHAR(500) not null, "REVIEWER" VARCHAR(100) not null, "RATING" INT not null, "GAMEID" INT not null);

ALTER TABLE DETAILS.DETAIL ADD CONSTRAINT FK_Detail_Game FOREIGN KEY(ID) REFERENCES GAMES.GAME(ID)
ALTER TABLE REVIEWS.REVIEW ADD CONSTRAINT FK_Review_Game FOREIGN KEY(GAMEID) REFERENCES GAMES.GAME(ID)